[reth]
db = "/mnt/data/eth/sepolia/reth/db"

[chain]
chain_id = 11155111
start_block = 4700000

[sync]
buffer_size = 1000

[http]
port = 8080
jwt_secret = "secret" # CHANGE THIS

[db]
url = "postgres://iron_indexer:iron-indexer&12345@localhost/iron_indexer"
